package com.book.demo.bookproject.model;

public enum Genres {
    ACTION, ADVENTURE,CLASSICS,COMIC,GRAPHIC,
    DETECTIVE, MYSTERY,FANTASY,HISTORICAL, HORROR,
    LITERARY,ROMANCE,SCIENCE,SUSPENSE, THRILLERS,
    BIOGRAPHIES, AUTOBIOGRAPHIES,COOKBOOKS, ESSAYS,
    HISTORY,MEMOIR,POETRY,SELF_HELP,TRUE_CRIME,FICTION;

}
